/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/house/level2_v3.glb
*/

import React, { useRef } from "react";
import { useThree } from "@react-three/fiber";
import useGltfKtx2 from "@/lib/useGltfKtx2";
import useAnimateModelOpacity from "@/lib/useAnimateModelOpacity";

export default function Level2({ opacity = 1, ...props }) {
  const { gl } = useThree();

  const { nodes, materials, scene } = useGltfKtx2(
    "/models/house/level2_v3.glb",
    gl,
  );

  useAnimateModelOpacity(opacity, scene);

  return <primitive object={scene} {...props} />;

  return (
    <group {...props} dispose={null}>
      <group position={[1.638, 4.547, -1.192]} scale={3.906}>
        <mesh geometry={nodes.平面066.geometry} material={materials.外墙蓝} />
        <mesh
          geometry={nodes.平面066_1.geometry}
          material={materials.厨房瓷砖}
        />
        <mesh
          geometry={nodes.平面066_2.geometry}
          material={materials.乳胶漆墙面}
        />
        <mesh
          geometry={nodes.平面066_3.geometry}
          material={materials.PaletteMaterial001}
        />
      </group>
      <mesh
        geometry={nodes.投影.geometry}
        material={materials.PaletteMaterial002}
        position={[0.801, 4.652, -1.437]}
        scale={2.971}
      />
      <mesh
        geometry={nodes["Obj3d66-19327086-346-309"].geometry}
        material={materials["3d66-CoronaLegacyMtl-19327086-035"]}
        position={[1.001, 4.692, -3.189]}
        scale={[1.83, 2.967, 2.203]}
      />
      <mesh
        geometry={nodes["Obj3d66-19327086-30-401004"].geometry}
        material={materials.木地板}
        position={[0.8, 5.974, -3.259]}
        scale={[2.056, 1.581, 1.581]}
      />
      <mesh
        geometry={nodes.吸顶灯01.geometry}
        material={materials.PaletteMaterial004}
        position={[0.725, 6.015, -0.817]}
        scale={[0.194, 0.359, 0.194]}
      />
      <mesh
        geometry={nodes.踢脚线002.geometry}
        material={materials.室外地板}
        position={[0.882, 3.268, -1.088]}
        scale={3.802}
      />
      <mesh
        geometry={nodes.地板003.geometry}
        material={materials.大理石地砖}
        position={[0.801, 3.228, -1.088]}
        scale={3.802}
      />
      <group
        position={[0.217, 4.676, -4.33]}
        rotation={[0, Math.PI / 2, 0]}
        scale={1.458}
      >
        <mesh
          geometry={nodes.平面094.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.平面094_1.geometry}
          material={materials.PaletteMaterial005}
        />
        <mesh
          geometry={nodes.平面094_2.geometry}
          material={materials.PaletteMaterial006}
        />
      </group>
      <mesh
        geometry={nodes.平面024.geometry}
        material={materials["材质.002"]}
        position={[0.404, 4.352, -4.343]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[1.411, 1.4, 1.293]}
      />
      <mesh
        geometry={nodes["2_table_full_mesh"].geometry}
        material={materials.PaletteMaterial001}
        position={[0.969, 4.475, -1.694]}
        rotation={[0.333, 1.453, 2.822]}
        scale={[3.342, 3.595, 3.052]}
      />
      <mesh
        geometry={nodes.平面016.geometry}
        material={materials.外墙白}
        position={[0.571, 4.758, -5.032]}
        scale={[1.207, 1.197, 1.207]}
      />
      <mesh
        geometry={nodes["Obj3d66-1230454-138-274"].geometry}
        material={materials.PaletteMaterial007}
        position={[-0.962, 5.552, -3.134]}
        rotation={[-Math.PI / 2, -0.028, Math.PI]}
        scale={[-0.19, 0.19, 0.19]}
      />
      <mesh
        geometry={nodes.空调002.geometry}
        material={materials["Mat3d66-14984029-337-97758"]}
        position={[2.647, 5.709, 0.677]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.043}
      />
      <instancedMesh
        args={[nodes.圆环003.geometry, materials.PaletteMaterial001, 11]}
        instanceMatrix={nodes.圆环003.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.圆环003_1.geometry, materials.PaletteMaterial003, 11]}
        instanceMatrix={nodes.圆环003_1.instanceMatrix}
      />
    </group>
  );
}

// useGLTF.preload("/models/house/level2_v3.glb");
