/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/house/level2_other_v3.glb
*/

import React, { useRef } from "react";
import { useThree } from "@react-three/fiber";
import useGltfKtx2 from "@/lib/useGltfKtx2";
import useAnimateModelOpacity from "@/lib/useAnimateModelOpacity";

export default function Level2Other({ opacity = 1, ...props }) {
  const { gl } = useThree();

  const { nodes, materials, scene } = useGltfKtx2(
    "/models/house/level2_other_v3.glb",
    gl,
  );

  useAnimateModelOpacity(opacity, scene);

  return <primitive object={scene} {...props} />;

  return (
    <group {...props} dispose={null}>
      <group position={[0.161, 4.547, -0.372]} scale={4.589}>
        <mesh
          geometry={nodes.平面013.geometry}
          material={materials.乳胶漆墙面}
        />
        <mesh
          geometry={nodes.平面013_1.geometry}
          material={materials.厨房瓷砖}
        />
        <mesh
          geometry={nodes.平面013_2.geometry}
          material={materials.PaletteMaterial001}
        />
      </group>
      <mesh
        geometry={nodes.踢脚线001.geometry}
        material={materials.室外地板}
        position={[-0.78, 3.268, 0.41]}
        scale={3.736}
      />
      <group position={[0.161, 4.619, 0.408]} scale={4.589}>
        <mesh
          geometry={nodes.平面025.geometry}
          material={materials.大理石地砖}
        />
        <mesh geometry={nodes.平面025_1.geometry} material={materials.木地板} />
      </group>
      <mesh
        geometry={nodes.楼梯001.geometry}
        material={materials.楼梯}
        position={[3.476, 3.629, -0.914]}
        scale={[0.56, 0.556, 0.56]}
      />
      <mesh
        geometry={nodes["Obj3d66-19327086-48-52001"].geometry}
        material={materials["3d66-VRayMtl-19327086-010"]}
        position={[-0.741, 4.637, 0.418]}
        rotation={[Math.PI / 2, 0, -0.006]}
        scale={[4.715, 3.703, 3.812]}
      />
      <mesh
        geometry={nodes["Obj3d66-19327086-30-401009"].geometry}
        material={materials.PaletteMaterial002}
        position={[-0.787, 5.838, 1.125]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[3.905, 3.003, 3.003]}
      />
      <mesh
        geometry={nodes.吸顶灯01001.geometry}
        material={materials.PaletteMaterial003}
        position={[-2.98, 6.082, -0.277]}
        scale={[1.883, 3.494, 1.883]}
      />
      <mesh
        geometry={nodes.卫生间_门框001.geometry}
        material={materials.PaletteMaterial004}
        position={[0.271, 4.308, -0.16]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[4.604, 4.513, 4.513]}
      />
      <mesh
        geometry={nodes.卫生间门001.geometry}
        material={materials.PaletteMaterial005}
        position={[0.66, 4.343, -0.178]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[-4.506, 4.506, 4.506]}
      />
      <mesh
        geometry={nodes.平面018.geometry}
        material={materials.外墙白}
        position={[0.627, 4.767, -0.174]}
        scale={[4.607, 4.571, 4.607]}
      />
      <mesh
        geometry={nodes.Toilet_l2_1_full_mesh.geometry}
        material={materials.PaletteMaterial001}
        position={[0.177, 4.511, -0.375]}
        scale={[4.576, 4.806, 5.121]}
      />
      <mesh
        geometry={nodes.空调004.geometry}
        material={materials["Mat3d66-14984029-337-97758"]}
        position={[-4.231, 5.853, -0.262]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.799}
      />
    </group>
  );
}

// useGLTF.preload("/models/house/level2_other_v3.glb");
