/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/house/level1_other_v3.glb
*/

import React, { useEffect, useRef } from "react";
import { useThree } from "@react-three/fiber";
import useGltfKtx2 from "@/lib/useGltfKtx2";

export default function Level1Other({ opacity = 1, ...props }) {
  const { gl } = useThree();

  const { nodes, materials, scene } = useGltfKtx2(
    "/models/house/level1_other_v3.glb",
    gl,
  );

  useEffect(() => {
    scene.traverse((n) => {
      if (n.isMesh) {
        n.material.transparent = true;
        n.material.opacity = opacity;
      }
    });
  }, [opacity, scene]);

  return <primitive object={scene} {...props} />;

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.墙体001.geometry}
        material={materials.乳胶漆墙面}
        position={[0.161, 2.961, -0.372]}
        scale={4.797}
      />
      <mesh
        geometry={nodes.踢脚线.geometry}
        material={materials.室外地板}
        position={[0.161, 0.13, -0.372]}
        scale={[4.589, 4.553, 4.589]}
      />
      <mesh
        geometry={nodes.地板.geometry}
        material={materials.木地板}
        position={[0.161, 2.445, -0.372]}
        scale={4.797}
      />
      <group
        position={[-0.516, 1.511, -0.362]}
        rotation={[0, Math.PI / 2, 0]}
        scale={4.515}
      >
        <mesh
          geometry={nodes.网格001.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.网格001_1.geometry}
          material={materials["Mat3d66-14984029-337-97758"]}
        />
      </group>
      <mesh
        geometry={nodes.楼梯.geometry}
        material={materials.楼梯}
        position={[3.913, 1.774, -0.222]}
        scale={[1.698, 1.684, 1.698]}
      />
      <mesh
        geometry={nodes.楼梯003.geometry}
        material={materials.PaletteMaterial002}
        position={[0.776, 3.026, -0.818]}
        scale={[4.305, 4.271, 4.305]}
      />
      <group position={[-4.42, 1.869, -2.503]} scale={[0.414, 0.414, 0.646]}>
        <mesh
          geometry={nodes.平面001.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh geometry={nodes.平面001_1.geometry} material={materials.画} />
      </group>
      <mesh
        geometry={nodes["Obj3d66-19327086-48-52002"].geometry}
        material={materials["3d66-VRayMtl-19327086-010"]}
        position={[-2.96, 1.482, -0.103]}
        rotation={[Math.PI / 2, 0, -0.006]}
        scale={[4.034, 3.168, 3.262]}
      />
      <mesh
        geometry={nodes["Obj3d66-19327086-49-840003"].geometry}
        material={materials["3d66-CoronaLegacyMtl-19327086-035"]}
        position={[1.742, 1.492, 0.429]}
        rotation={[-Math.PI / 2, 0, 3.135]}
        scale={[6.918, 3.711, 3.711]}
      />
      <mesh
        geometry={nodes.卫生间_门框.geometry}
        material={materials.PaletteMaterial004}
        position={[0.271, 1.173, 0.44]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[3.991, 3.913, 3.913]}
      />
      <mesh
        geometry={nodes.卫生间门.geometry}
        material={materials.PaletteMaterial005}
        position={[0.271, 1.188, -0.275]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[-4.604, 4.604, 4.604]}
      />
      <mesh
        geometry={nodes.窗沿02.geometry}
        material={materials.外墙白}
        position={[0.268, 1.623, 0.427]}
        scale={4.044}
      />
      <mesh
        geometry={nodes["1_alice_horizontal_full_mesh"].geometry}
        material={materials.PaletteMaterial002}
        position={[-0.088, 1.104, 0.483]}
        rotation={[1.73, 0.392, -0.332]}
        scale={5.011}
      />
      <mesh
        geometry={nodes.吸顶灯01004.geometry}
        material={materials.PaletteMaterial006}
        position={[-2.98, 2.943, -0.277]}
        scale={[1.883, 3.494, 1.883]}
      />
    </group>
  );
}

// useGLTF.preload("/models/house/level1_other_v3.glb");
